# Generated by Django 5.2.8 on 2025-11-16 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GamesFeedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(db_index=True, max_length=100, verbose_name='Hashtag')),
                ('text', models.TextField(verbose_name='Text')),
                ('up_vote_count', models.IntegerField(max_length=10, verbose_name='UpVote Count')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('badge_letter', models.CharField(max_length=5, verbose_name='Badge Letter')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Games Feedback',
                'verbose_name_plural': 'Games Feedbacks',
            },
        ),
    ]
