# Generated by Django 5.2.8 on 2025-11-16 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_alter_gamesfeedbacks_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesfeedbacks',
            name='up_vote_count',
        ),
    ]
