# Generated by Django 5.2.8 on 2025-11-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0003_remove_gamesfeedbacks_up_vote_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesfeedbacks',
            name='hashtag',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Hashtag'),
        ),
    ]
