# Generated by Django 5.2.8 on 2025-11-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0004_alter_gamesfeedbacks_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesfeedbacks',
            name='badge_letter',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Badge Letter'),
        ),
    ]
