# Generated by Django 5.2.8 on 2025-11-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0005_alter_gamesfeedbacks_badge_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesfeedbacks',
            name='badge_letter',
            field=models.CharField(blank=True, editable=False, max_length=5, null=True, verbose_name='Badge Letter'),
        ),
        migrations.AlterField(
            model_name='gamesfeedbacks',
            name='hashtag',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=100, null=True, verbose_name='Hashtag'),
        ),
    ]
