# Generated by Django 5.2.8 on 2025-11-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0006_alter_gamesfeedbacks_badge_letter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesfeedbacks',
            name='create_date',
            field=models.DateField(auto_now_add=True, verbose_name='Create Date'),
        ),
    ]
