# Generated by Django 5.2.8 on 2025-11-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0007_alter_gamesfeedbacks_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesfeedbacks',
            name='upvote_count',
            field=models.IntegerField(default=0, max_length=10, verbose_name='Upvote Count'),
        ),
    ]
