# Generated by Django 5.2.8 on 2025-11-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0009_feedbackupvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesfeedbacks',
            name='upvote_count',
            field=models.IntegerField(default=0, verbose_name='Upvote Count'),
        ),
    ]
