# Generated by Django 5.2.8 on 2025-11-20 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0010_alter_gamesfeedbacks_upvote_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedbackUpvote',
        ),
    ]
